MANIFEST.in
Makefile
requirements.txt

Misspelled as attr. Include requirements.txt in the MANIFEST.
**Reminders**

Fix broken requirement name for attrs

---

README.rst

Fix typo on Boulde description in README.md file.
It said `break` where it should be saying `bread`.
**Reminders**

Fix typo on Boule description in README

---

boule/ellipsoid.py
boule/tests/test_ellipsoid.py
doc/_templates/autosummary/class.rst
doc/references.rst

Add methods to Ellipsoid to transform coordinates from geodetic to
spherical and back again. Copied from Harmonica. Added as methods to
avoid passing "ellipsoid" all the time or having to use a global
ellipsoid.
**Reminders**

Spherical to geodetic and inverse transformations

---

.azure-pipelines.yml
.travis.yml
setup.py

Add builds using Python 3.8 to the CIs so we know tests pass. On
setup.py, only need to add metadata flags saying that we're compatible
with 3.8.
**Reminders**

Add CI testing and setup.py flags for Python 3.8

---

Makefile
boule/earth.py
boule/tests/test_ellipsoid.py
doc/api/index.rst
doc/ellipsoids.rst
doc/index.rst

It's awkward to have to use `WGS84()` when all ellipsoids don't really
take any arguments. Make them instances of the `Ellipsoid` class instead
of subclasses to get rid of `()`. Move the list of ellipsoids to a
separate documentation page and move doctests to that page. Add required
pytest configuration to the Makefile so we can run the doctests in the
rst sources.
**Reminders**

Make ellipsoids instances not subclasses

---

.codecov.yml

Was using `comment: off` in the configuration when it should be
`comment: false`.
**Reminders**

Disable codecov PR comments correctly

---

boule/ellipsoid.py

An arctangent term had a division by the cosine of latitude that would
be zero in the poles (causing a zero division warning). The values are
correct by putting the cosine in the second argument of arctan2 makes it
go away.
**Reminders**

Avoid division by cos latitude in normal gravity

---

README.rst
doc/changes.rst
doc/install.rst

Was missing instructions for conda and pip. Mark a new bug fix release
to update the latest documentation pages only.
**Reminders**

Update install instructions and mark 0.1.1 release

---

boule/ellipsoid.py
boule/tests/test_ellipsoid.py

Add private method to `boule.Ellipsoid` for computing the prime vertical radius.
The definition of the prime vertical radius can be seen on [Vermeille (2002)](https://doi.org/10.1007/s00190-002-0273-6)  and [Vajda (2004)](https://d1wqtxts1xzle7.cloudfront.net/45194692/On_evaluation_of_Newton_integrals_in_geo20160429-31556-16b23iv.pdf?1461926098=&response-content-disposition=inline%3B+filename%3DOn_evaluation_of_Newton_integrals_in_geo.pdf&Expires=1594246043&Signature=G0FRusq9DVc1eSllnrFGZUufrskJdDQgXpOn8pzITqSQVvnwflK2a9nSZqUbfqD2msqsDEVbUiaNeUKEeXYentp3GiMmEXE~P-Dt9KddO0-AcaXf-WjTUWeJb5wmnFKFAFANWhNS4x9IlVY2NdqPP2U-Ide6KxA7yNGN-JhQ1i-OvQEG8dSAgvYJTDKhdodlWcLmn1zYtlDGtde3IMEWT2JpB-JzoXRF8aJbEMTKXEGvnb4FMgGxWsfsCmFry67Zu3pAebeRrvGhY-JYuODa2bGqr8nu8CyO0KuOV5eoVFLI2zFZWIXwDH1njr~2kLhvJwBMm9q4 …

Add method for computing prime vertical radius

---

boule/ellipsoid.py
boule/tests/test_ellipsoid.py

This is the distance from the center of the ellipsoid to its surface as
a function of geodetic latitude.
Fixes #34 
**Reminders**:

Add a method for the ellipsoid geocentric radius

---

boule/sphere.py
boule/tests/test_sphere.py

Fix the method that computes the norm of the gravity acceleration vector
on the equator of a sphere. The method used to return only the
gravitational attraction term, without the centrifugal acceleration
term. Add the additional term and update the test function, which now
compares gravity on poles and equator with the normal gravity formula.
**Reminders**:

Fix missing centrifugal term for sphere gravity at the equator

---

boule/ellipsoid.py

The `check_*` methods were appearing in the API list, which isn't
desirable since they are not meant to be used directly. Make them
private (with a leading `_`) to avoid this. While we're at it, use
f-strings to make error messages shorter.
**Reminders**:

Make parameter validation methods private

---

.github/workflows/continuous-integration.yml

It's a bit wasteful to store all this data that we will very likely
never use (downloading the cached page displaying them locally requires
a lot of clicking). So we might as well leave this out for now.
**Reminders**:

Stop saving the docs HTML as build artifacts

---

.github/workflows/deploy.yml

In #59, we inadvertently reverted the `sed` command in the `deploy`
workflow to the versioneer version. This reintroduces the correct
command from #61.
**Reminders**:

Revert change to "sed" command in deploy workflow

---

.github/workflows/docs.yml
.github/workflows/pypi.yml
.github/workflows/test.yml

Instead of running the docs build every time, leave it to one workflow
which can then reuse the HTML artifacts to deploy. Separate the PyPI
deploy in a separate workflow as well.
**Reminders**:

Refactor workflows to separate building the docs

---

boule/ellipsoid.py
boule/sphere.py
boule/tests/test_ellipsoid.py
boule/tests/test_sphere.py

This PR adds an option to return gamma in SI units for the normal_gravity method in both the ellipsoid and sphere classes as per #46 .
I have included an example in the sphere docstring and added tests for both classes.
**Reminders**:

Add option to return normal gravity in SI units

---

.github/workflows/test.yml
noxfile.py
setup.py

Fixes https://github.com/fatiando/boule/issues/85.
Includes and closes #86.
Related to fatiando/maintenance#15
Skip macOS as it fails building NumPy from source. Can be unexcluded when NumPy has released wheels for macOS.
**Reminders**:
- [n/a] Add tests for new features or tests that would have caught the bug that you're fixing.
- [n/a] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [n/a] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [n/a] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

Add support for Python 3.9 and 3.10

---

boule/ellipsoid.py
boule/sphere.py
boule/tests/test_ellipsoid.py

Check if normal gravity is computed on internal point 

---

.github/workflows/test.yml
doc/compatibility.rst
doc/index.rst
setup.cfg

Following the guidance in fatiando/community#40 and NEP29, support all 
minor versions from the past 24 months. This means numpy >= 1.19
and attrs >= 19.3. Add CI tests for the oldest versions but test only 
oldest supported versions with the oldest Python and vice-versa because
numpy doesn't supply wheels for old versions on new Python. It also
saves CI compute time and should be more than enough of a safeguard.
Related to fatiando/community#40

Specify oldest supported version of dependencies

---

README.md

The link to the LICENSE.txt file was still using RST syntax and the
warning about project status being alpha and to expect breaking changes
was missing from the README.
Fixes #115

Fix license link + compatibility warning in README

---

boule/_ellipsoid.py
boule/tests/test_ellipsoid.py
boule/tests/test_sphere.py
doc/ellipsoids/wgs84.rst

This is only used in the calculation of gravity at the poles and
equators and has no physical meaning. It's just a convenience used
internally. So make it private to clean up the interface.
Backwards incompatible but changes of someone actually using this value are extremely low.

Make Ellipsoid.emm attribute private (i.e., _emm)

---

doc/Makefile

Add a new `serve` target in `doc/Makefile` so it's easy to serve the docs locally.

Add serve target in doc/Makefile

---

doc/glossary.rst
doc/overview.rst

Addition requested in #138
Fixes #138

Add definition of “co-located grids” to the glossary

---

doc/index.rst

It was still pointing to the old subdomain redirect which is now invalid. Point to the main contact page on fatiando.org instead.

Update contact link in the docs side bar

---

.github/workflows/test.yml
doc/install.rst
setup.cfg

We're over the deadline for dropping support according to NEP29.
Fixes #135

Drop support for Python 3.6

---

AUTHORS.md

Add Blazej Bucha to `AUTHORS.md` .
Relevant to #105

Add Blazej Bucha to AUTHORS.md

---

.github/dependabot.yml

The bot sends PRs when new versions of the Actions we use are available.

Use Dependabot to manage updates to GitHub Actions

---

.github/workflows/pypi.yml

Replaces the API tokens. This is the way PyPI recommends deploying.
Part of https://github.com/fatiando/community/issues/141

Use Trusted Publisher to deploy to PyPI

---

.github/workflows/docs.yml
doc/conf.py
doc/index.rst
doc/overview.rst
doc/user_guide/gravity_disturbance.rst
doc/user_guide/normal_gravity.rst
env/requirements-docs.txt
environment.yml

Use the latest version of sphinx, the docs theme, and the plugins we use. Also update GMT and PyGMT. PyGMT v0.11 in particular requires setting the display method when using jupyter-sphinx to get the figures displayed properly. This is done globally for each page using a hidden cell.

Update the version of sphinx and its plugins

---

doc/install.rst

Fix minor typo in the documentation pages for installing Boule.

Fix typo in installation instructions

---

boule/_constants.py
boule/_ellipsoid.py
boule/_sphere.py
boule/_triaxialellipsoid.py

This PR addresses the issue https://github.com/fatiando/boule/issues/164 concerning the addition of `mass`, `mean_density`, and `volume_equivalent_radius` properties to the ellipsoid classes. The following changes were made:
* Created a top level file `_constants.py` to house to the gravitational constant `G` that is imported into the three ellipsoid classes.
* Added the properties `mass`, `mean_density`, and `volume_equivalent_radius` to each of the three ellipsoid classes.
* Clarified the docstrings of `mean radius`: This is, in fact, *not* the mean radius of the sphere (i.e., the degree 0 coefficient of the shape), but rather is the mean of the semi-axes (a + b + c)/3.  This is defined as R_1 in WGS84 Moritz1988.
Comments
* The mathematical equation for the `volume_equivalent_radius` …

Add mass, mean_density, and volume_equivalent_radius properties

---

.github/workflows/test.yml
doc/compatibility.rst
doc/install.rst
pyproject.toml

It's long overdue and we no longer need to support it. Upgrade the project setting, CI matrix, and version compatibility docs.

Drop support for Python 3.7

---

boule/_ellipsoid.py
boule/_sphere.py
boule/_triaxialellipsoid.py

This PR adds a property that computes the "true" mean radius of the ellipsoid as described in #174. The following changes were made:
1. The old Sphere/Ellipsoid/TriaxialEllipsoid `mean_radius` properties were renamed to `semiaxes_mean_radius` ($R_1$).
2. A new property `mean_radius` ($R_0$) was added that computes the mean radius using Gauss Legendre quadrature. The quadrature routine is taken directly from numpy, and requires no additional imports.
**Note:**
There is a single parameter that needs to be defined, which is the number of quadrature points to use. (For triaxial ellipsoids, I set the number of points in longitude to be twice that in latitude). For the ellipsoids that are already defined in boule, tests show that about n=10 is sufficient to get machine precision results. Tests …

Add true mean radius for Sphere,  Ellipsoid and TriaxialEllipsoid classes

---

boule/_ellipsoid.py
boule/_sphere.py
boule/tests/test_ellipsoid.py
boule/tests/test_sphere.py

**Squash and Merge comment**
Add `semimedium_axis` and `semimajor_axis_longitude`  to the Sphere and Ellipsoid classes for compatibility with the `TriaxialEllipsoid`. Don't use mathematical symbols for the `semimedium_axis`. Remove the "Added for compatibility with pymap3d" comment in some of the properties.
---
This PR adds the property `semimedium_axis`and `semimajor_axis_longitude`  to the Sphere and Ellipsoid classes. This is done for compatibility. I note that the Sphere class already had semiminor and semimajor axes set.
Furthermore, I have removed "Added for compatibility with pymap3d" from the docstring, as I encountered this compatibility problem in pyshtools... In many cases, people will treat (Sphere, Ellipsoid, TriaxialEllipsoid) as just a boule instance, and won't care which …

Add `semimedium_axis` property to sphere and ellipsoid

---

boule/_ellipsoid.py

There was a note in the docstring about heights and using pymap3d but it doesn't seem to make much sense since the definition of the radius is distance to the surface of the ellipsoid. Remove the reference to avoid causing confusion.

Remove reference to height in geocentric_radius
