- README.rst
Include an explanation of why the name Boule.
**Reminders**
> Add project goals and description to README

- boule/__init__.py
- boule/earth.py
- doc/ellipsoids.rst
Use the definition and derived values from the Physical Geodesy book.
**Reminders**
> Add the GRS80 Earth ellipsoid

- boule/__init__.py
- boule/realizations.py
- doc/ellipsoids/index.rst
- doc/ellipsoids/mars.rst
- doc/references.rst
- tutorials/normal_gravity.py
Based on the numbers is Ardalan et al. (2009). Include a plot of normal
gravity on Mars in the tutorial as well.
**Reminders**
> Add an ellipsoid for Mars

- README.rst
- doc/changes.rst
> Add changelog entry for 0.1.0 release

- .azure-pipelines.yml
The 10.13 images we were using are now disabled.
**Reminders**:
> Update Azure MacOS to 10.15

- AUTHORS.md
@santisoler you weren't in the AUTHORS file so I took the liberty here. Are you OK with being added? Wanted to do this before the release.
**Reminders**:
> Add Santiago to AUTHORS file

- README.rst
- doc/changes.rst
Feature release with two new methods and a typo fix.
Waiting on #38 to merge and then release.
**Reminders**:
> Changelog entry for v0.2.0

- README.rst
It's an easy way to find the feedstock repository. Also use .com instead of .org for Travis.
**Reminders**:
> Add conda-forge badge to the README

- boule/tests/test_ellipsoid.py
- boule/tests/test_sphere.py
- boule/tests/utils.py
Add tests functions to compare ellipsoids' normal gravity on their surface against the Somigliana equation.
**Reminders**:
> Tests normal gravity against Somigliana equation

- boule/__init__.py
- boule/ellipsoid.py
- boule/realizations.py
- boule/sphere.py
- boule/tests/__init__.py
- boule/tests/test_ellipsoid.py
- boule/tests/test_sphere.py
- boule/tests/utils.py
- boule/version.py
- doc/conf.py
- noxfile.py
- setup.py
- tutorials/normal_gravity.py
- tutorials/overview.py
Related to fatiando/maintenance#10
**Reminders**:
> Add license and copyright notice to every .py file

- boule/__init__.py
- boule/realizations.py
- doc/ellipsoids/index.rst
- doc/ellipsoids/mercury.rst
- doc/ellipsoids/moon.rst
- doc/ellipsoids/venus.rst
- doc/references.rst
Added Mercury and Moon Spheroids, plus documentation.
This completes #53 .
**Reminders**:
> Add mercury and moon spheres to realizations.py

- boule/ellipsoid.py
- boule/sphere.py
- boule/tests/test_ellipsoid.py
- boule/tests/test_sphere.py
- boule/tests/utils.py
I ran `make format` and it changed the power operators on some files according to the new version of Black
> Fix the format of some files 

- .github/workflows/docs.yml
- .github/workflows/pypi.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
- README.rst
- doc/conf.py
- doc/index.rst
- doc/install.rst
Rename the development branch from `master` to `main` in the GitHub Actions configuration and documentation.
#106
> Rename master branch to main

- AUTHORS.md
I add me as author in AUTHOR.md file
> Add new author

- boule/_ellipsoid.py
Checked against approximate values reported at
https://en.wikipedia.org/wiki/Earth
Partial for #75
> Add the volume property for the ellipsoid

- doc/changes.rst
- doc/versions.rst
New minor release with new features, improved docs, and some breaking changes.
#133
> Add changelog for v0.4.0

- doc/overview.rst
> Fix typo in overview docs page

- .mailmap
- doc/changes.rst
- doc/versions.rst
This is a maintenance release with some documentation fixes and undoing a deprecation. Create a `.mailmap` to avoid having duplicate entries for authors when using `git shortlog`.
See #143
> Add changelog entry for v0.4.1

- .github/workflows/docs.yml
- .github/workflows/pypi.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
- setup.cfg
Extend support for Python 3.11 and bump versions of GitHub Actions.
> Extend support for Python 3.11

- boule/_ellipsoid.py
- boule/tests/test_ellipsoid.py
Minor changes in a couple of files.
> Update Black format to version 24.2

- boule/_sphere.py
Nothing fancy, just output the volume.
Fixes #75
> Add a volume property for the Sphere

- .github/workflows/docs.yml
- .github/workflows/pypi.yml
- .github/workflows/style.yml
- .github/workflows/test.yml
- environment.yml
- pyproject.toml
Add the metadata in pyproject.toml and bump the version on the CI.
> Extend support to Python 3.12

- AUTHORS.md
Mine was the only one that wasn't a link
> Add link to Leo's ORCID

- doc/changes.rst
- doc/versions.rst
Add changelog for Boule v0.5.0 and add link to the new docs in `versions.rst`.
Related to #215
> Add changelog for v0.5.0
